// components/GuestForm.tsx
'use client'

import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { supabase } from '@/lib/supabase'
import { getInvitationTemplateUi } from '@/lib/templates'
import type { InvitationTemplateId } from '@/lib/templates'

type GuestFormProps = {
    invitationId: string
    template: InvitationTemplateId
}

export default function GuestForm({ invitationId, template }: GuestFormProps) {
    const [name, setName] = useState('')
    const [message, setMessage] = useState('')
    const [loading, setLoading] = useState(false)
    const [sent, setSent] = useState(false)
    const [error, setError] = useState('')
    const ui = getInvitationTemplateUi(template)

    const handleSubmit = async () => {
        const trimmedName = name.trim()
        const trimmedMessage = message.trim()

        if (!trimmedName || !trimmedMessage) {
            setError('اكتب اسمك ورسالتك قبل الإرسال')
            return
        }

        setLoading(true)
        setError('')

        const { error: submitError } = await supabase.from('guest_messages').insert([
            { invitation_id: invitationId, name: trimmedName, message: trimmedMessage },
        ])

        setLoading(false)

        if (submitError) {
            setError('حدث خطأ أثناء الإرسال، حاول مرة أخرى')
            return
        }

        setSent(true)
        setName('')
        setMessage('')

        setTimeout(() => setSent(false), 4000)
    }

    return (
        <div className="mt-10 w-full">
            <div className="mb-6 flex items-center gap-4">
                <div className={`h-px flex-1 ${ui.formLine}`} />
                <p className={`font-cairo text-xs font-bold ${ui.formTitle}`}>
                    رسالتك لنا
                </p>
                <div className={`h-px flex-1 ${ui.formLine}`} />
            </div>

            <div className={`space-y-4 rounded-3xl border p-5 sm:p-6 ${ui.formPanel}`}>
                <label className="block">
                    <span className="sr-only">اسمك</span>
                    <input
                        dir="rtl"
                        placeholder="اسمك"
                        value={name}
                        onChange={(event) => {
                            setName(event.target.value)
                            setError('')
                        }}
                        className={`w-full rounded-2xl border px-5 py-3 font-cairo text-sm outline-none transition focus:ring-2 ${ui.formInput}`}
                    />
                </label>

                <label className="block">
                    <span className="sr-only">رسالتك للعروسين</span>
                    <textarea
                        dir="rtl"
                        rows={4}
                        placeholder="رسالتك للعروسين..."
                        value={message}
                        onChange={(event) => {
                            setMessage(event.target.value)
                            setError('')
                        }}
                        className={`w-full resize-none rounded-2xl border px-5 py-3 font-cairo text-sm outline-none transition focus:ring-2 ${ui.formInput}`}
                    />
                </label>

                <motion.button
                    type="button"
                    onClick={handleSubmit}
                    disabled={loading || !name.trim() || !message.trim()}
                    whileTap={{ scale: 0.97 }}
                    whileHover={{ scale: 1.01 }}
                    className={`min-h-12 w-full rounded-2xl py-3 font-cairo text-sm font-bold transition-all duration-300 disabled:cursor-not-allowed disabled:opacity-50 ${ui.formButton}`}
                >
                    {loading ? 'جار الإرسال...' : 'إرسال الرسالة'}
                </motion.button>

                <AnimatePresence mode="wait">
                    {error && (
                        <motion.div
                            key="error"
                            initial={{ opacity: 0, y: 8 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -8 }}
                            className="pt-1 text-center font-cairo text-sm text-rose-400"
                        >
                            {error}
                        </motion.div>
                    )}

                    {sent && (
                        <motion.div
                            key="success"
                            initial={{ opacity: 0, y: 8 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -8 }}
                            className={`pt-1 text-center font-cairo text-sm ${ui.formSuccess}`}
                        >
                            تم إرسال رسالتك بنجاح
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    )
}

// src/app/components/guest-form/guest-form.component.ts
import { Component, Input, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  trigger,
  transition,
  style,
  animate,
} from '@angular/animations';
import { SupabaseService } from '../../core/services/supabase.service';
import { getInvitationTemplateUi, InvitationTemplateId } from '../../lib/templates';

@Component({
  selector: 'app-guest-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  animations: [
    trigger('fadeSlide', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(8px)' }),
        animate('250ms ease-out', style({ opacity: 1, transform: 'translateY(0)' })),
      ]),
      transition(':leave', [
        animate('200ms ease-in', style({ opacity: 0, transform: 'translateY(-8px)' })),
      ]),
    ]),
  ],
  template: `
    <div class="mt-10 w-full">
      <!-- Section title -->
      <div class="mb-6 flex items-center gap-4">
        <div class="h-px flex-1" [class]="ui.formLine"></div>
        <p class="font-cairo text-xs font-bold" [class]="ui.formTitle">رسالتك لنا</p>
        <div class="h-px flex-1" [class]="ui.formLine"></div>
      </div>

      <!-- Form panel -->
      <div class="space-y-4 rounded-3xl border p-5 sm:p-6" [class]="ui.formPanel">
        <!-- Name input -->
        <label class="block">
          <span class="sr-only">اسمك</span>
          <input
            dir="rtl"
            placeholder="اسمك"
            [(ngModel)]="name"
            (ngModelChange)="error.set('')"
            class="w-full rounded-2xl border px-5 py-3 font-cairo text-sm outline-none transition focus:ring-2"
            [class]="ui.formInput"
          />
        </label>

        <!-- Message textarea -->
        <label class="block">
          <span class="sr-only">رسالتك للعروسين</span>
          <textarea
            dir="rtl"
            rows="4"
            placeholder="رسالتك للعروسين..."
            [(ngModel)]="message"
            (ngModelChange)="error.set('')"
            class="w-full resize-none rounded-2xl border px-5 py-3 font-cairo text-sm outline-none transition focus:ring-2"
            [class]="ui.formInput"
          ></textarea>
        </label>

        <!-- Submit button -->
        <button
          type="button"
          (click)="handleSubmit()"
          [disabled]="loading() || !name.trim() || !message.trim()"
          class="min-h-12 w-full rounded-2xl py-3 font-cairo text-sm font-bold transition-all duration-300 disabled:cursor-not-allowed disabled:opacity-50 active:scale-[0.97] hover:scale-[1.01]"
          [class]="ui.formButton"
        >
          {{ loading() ? 'جار الإرسال...' : 'إرسال الرسالة' }}
        </button>

        <!-- Error message -->
        @if (error()) {
          <div @fadeSlide class="pt-1 text-center font-cairo text-sm text-rose-400">
            {{ error() }}
          </div>
        }

        <!-- Success message -->
        @if (sent()) {
          <div @fadeSlide class="pt-1 text-center font-cairo text-sm" [class]="ui.formSuccess">
            تم إرسال رسالتك بنجاح ✓
          </div>
        }
      </div>
    </div>
  `,
})
export class GuestFormComponent {
  @Input() invitationId!: string;
  @Input() template!: InvitationTemplateId;

  name = '';
  message = '';
  loading = signal(false);
  sent = signal(false);
  error = signal('');

  constructor(private supabase: SupabaseService) {}

  get ui() {
    return getInvitationTemplateUi(this.template);
  }

  async handleSubmit(): Promise<void> {
    const trimmedName = this.name.trim();
    const trimmedMessage = this.message.trim();

    if (!trimmedName || !trimmedMessage) {
      this.error.set('اكتب اسمك ورسالتك قبل الإرسال');
      return;
    }

    this.loading.set(true);
    this.error.set('');

    const { error: submitError } = await this.supabase.client
      .from('guest_messages')
      .insert([{ invitation_id: this.invitationId, name: trimmedName, message: trimmedMessage }]);

    this.loading.set(false);

    if (submitError) {
      this.error.set('حدث خطأ أثناء الإرسال، حاول مرة أخرى');
      return;
    }

    this.sent.set(true);
    this.name = '';
    this.message = '';

    setTimeout(() => this.sent.set(false), 4000);
  }
}
